# arithmoi bound is actually needed because they removed the powerMod function
# the rest are just the result of fiddling until stack build worked

resolver: lts-3.0
allow-newer: true
extra-deps:
- arithmoi-0.5.0.1
- exact-pi-0.5.0.1
- integer-logarithms-1.0.3
- numtype-dk-0.5.0.2
- ../star-crypto
